#!/bin/bash

echo "Parsing the CSS files..."
python3 parse.py

echo "Showing Results"
cp results.json viewer/results.json
xdg-open http://localhost:8000
cd viewer && python3 -m http.server 8000 --bind 127.0.0.1